export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "380abe66": [() => import(/* webpackChunkName: "380abe66" */ "@site/src/pages/login.js"), "@site/src/pages/login.js", require.resolveWeak("@site/src/pages/login.js")],
  "393be207": [() => import(/* webpackChunkName: "393be207" */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  "5dc2636f": [() => import(/* webpackChunkName: "5dc2636f" */ "@site/docs/adoawdka.md"), "@site/docs/adoawdka.md", require.resolveWeak("@site/docs/adoawdka.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "dc44a004": [() => import(/* webpackChunkName: "dc44a004" */ "@site/src/pages/edit-projects.js"), "@site/src/pages/edit-projects.js", require.resolveWeak("@site/src/pages/edit-projects.js")],
  "e671c079": [() => import(/* webpackChunkName: "e671c079" */ "@site/src/pages/addProjects.js"), "@site/src/pages/addProjects.js", require.resolveWeak("@site/src/pages/addProjects.js")],
  "ee7ef1d2": [() => import(/* webpackChunkName: "ee7ef1d2" */ "@site/src/pages/projects.js"), "@site/src/pages/projects.js", require.resolveWeak("@site/src/pages/projects.js")],
  "f7d1c8f5": [() => import(/* webpackChunkName: "f7d1c8f5" */ "@site/src/pages/coding.js"), "@site/src/pages/coding.js", require.resolveWeak("@site/src/pages/coding.js")],};
